tab:
  default:
    priority: 0
    commands: []
blocked_command_default_actions:
  - "message: &8[&b&lECB&8] &cYou don't have permissions to use that command."
use_commands_as_whitelist: false
commands:
  - "/bungee"
  - "/server"
  - "/lpb"
custom_commands_actions:
  example1:
    commands:
      - "/bungee"
    actions:
      - "message: &8[&b&lECB&8] &cYou can't see the BungeeCord version!"