main: ecb.ajneb97.spigot.EasyCommandBlocker
version: 1.7.4
name: EasyCommandBlocker
api-version: 1.13
softdepend: [ProtocolLib,ViaVersion]
author: Ajneb97

commands:
  easycommandblocker:
    description: Main command of EasyCommandBlocker
    aliases: [ecb]