main: ecb.ajneb97.spigot.EasyCommandBlocker
version: ${project.version}
name: EasyCommandBlocker
api-version: 1.13
softdepend: [ViaVersion, ProtocolLib, packetevents]
author: Ajneb97

commands:
  easycommandblocker:
    description: Main command of EasyCommandBlocker
    aliases: [ecb]